version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nestjs-app:$CODEBUILD_BUILD_NUMBER .
      - echo Pushing Docker image...
      - docker push <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nestjs-app:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"nestjs-app","imageUri":"%s"}]' <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nestjs-app:$CODEBUILD_BUILD_NUMBER > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
