import { ObjectType, Field } from '@nestjs/graphql';
import { ItineraryCategory, ItineraryType } from '../enums';
import { IPlace } from './IPlace.entity';

/**
 * Represents an itinerary entity.
 */
@ObjectType()
export class GeneratedItinerary {
  @Field(() => String, {
    description: 'ID of the itinerary',
    nullable: false,
  })
  id: string;

  @Field(() => String, {
    description: 'Title of the itinerary',
    nullable: false,
  })
  itinerary_title: string;

  @Field(() => String, { description: 'Description of the itinerary' })
  itinerary_description: string;

  /**
   * Dynamic will be generated by the system, Custom will be created by the user.
   *
   * @type {ItineraryCategory}
   * @description
   */
  @Field(() => ItineraryCategory, {
    description: 'Category of the itinerary',
    nullable: false,
  })
  itinerary_category: ItineraryCategory;

  @Field(() => ItineraryType, {
    description: 'type of itinerary',
    nullable: false,
  })
  itinerary_type: ItineraryType;

  /**
   * A list of Google Maps Places
   *
   * @type {IPlace[]}
   * @description List of places from places v1
   */
  @Field(() => [IPlace], {
    description:
      'List of primary place types for the itinerary from https://developers.google.com/maps/documentation/places/web-service/place-types',
    nullable: false,
  })
  activities: [IPlace];
}
