import { ObjectType, Field } from '@nestjs/graphql';
// import { ItineraryCategory, ItineraryType } from '../enums';
import { Itinerary, ItineraryCategory, ItineraryType } from '@prisma/client';

/**
 * Represents an itinerary entity.
 */
@ObjectType()
export class ItineraryEntity implements Itinerary {
  @Field(() => String, {
    description: 'Teh date the itinerary was created',
    nullable: false,
  })
  createdAt: Date;

  @Field(() => String, {
    description: 'Teh date the itinerary was last updated',
    nullable: false,
  })
  updatedAt: Date;

  @Field(() => String, {
    description: 'The ID of the user who created the itinerary',
    nullable: false,
  })
  userId: string;

  @Field(() => String, {
    description: 'ID of the itinerary',
    nullable: false,
  })
  id: string;

  @Field(() => String, {
    description: 'Title of the itinerary',
    nullable: false,
  })
  itinerary_title: string;

  @Field(() => String, { description: 'Description of the itinerary' })
  itinerary_description: string;

  /**
   * Dynamic will be generated by the system, Custom will be created by the user.
   *
   * @type {ItineraryCategory}
   * @description
   */
  @Field(() => ItineraryCategory, {
    description: 'Category of the itinerary',
    nullable: false,
  })
  itinerary_category: ItineraryCategory;

  @Field(() => ItineraryType, {
    description: 'type of itinerary',
    nullable: false,
  })
  itinerary_type: ItineraryType;

  /**
   * A list of Google Maps Place Types associated with the itinerary.
   *
   * @type {string[]}
   * @description List of primary place types for the itinerary from https://developers.google.com/maps/documentation/places/web-service/place-types
   */
  @Field(() => [String], {
    description:
      'List of primary place types for the itinerary from https://developers.google.com/maps/documentation/places/web-service/place-types',
    nullable: true,
  })
  google_places_primary_place_types: string[];

  /**
   * A list of Google Maps Place ids associated with the itinerary.
   *
   * @type {string[]}
   * @description 'List of place ids for the itinerary from https://developers.google.com/maps/documentation/places/web-service/place-id',

   */
  @Field(() => [String], {
    description:
      'List of place ids for the itinerary from https://developers.google.com/maps/documentation/places/web-service/place-id',
  })
  google_places_place_ids: string[];

  @Field(() => String, {
    description: 'An AI Generated image URL for the itinerary',
    nullable: false,
  })
  itinerary_thumbnail: string;
}
